FROM node:20-slim

WORKDIR /usr/src/app

# Instala dependencias
COPY package*.json ./ 
# ⬇️ CORRECCIÓN: Forzamos el registro público y evitamos el uso de configuraciones locales.
RUN npm install --omit=dev --no-fund --registry=https://registry.npmjs.org/

# Copia código fuente
COPY . .

EXPOSE 3001

# Inicia la aplicación (la ruta es relativa al WORKDIR /usr/src/app)
CMD [ "node", "server/server.js" ]